name: Run Tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run tests
      run: ./gradlew test -Psuite=UserTestSuite_test.xml

    - name: Upload TestNG results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results/test

    - name: Test Report
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: build/test-results/test/*.xml  # Path to your TestNG report
        reporter: junit  # Use 'junit' since TestNG reports are JUnit-compatible
        fail-on-error: true
