name: Run Tests

on: 
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every night

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'  # Set JDK version to 11

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew  # Ensure the Gradle wrapper is executable

    - name: Run tests
      run: ./gradlew test -Psuite=UserTestSuite_test.xml
