name: Run RestAssured Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permission for Gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -Psuite=UserTestSuite_test.xml

    - name: Upload test results
    uses: actions/upload-artifact@v3
    with:
      name: junit-test-results
      path: build/test-results/test

    - name: Test Report
    if: always()  # Ensure this step runs even if tests fail
    uses: dorny/test-reporter@v1
    with:
      name: Test Results
      path: build/test-results/test/*.xml  # Path to the generated XML reports
      reporter: testng  # Correct reporter type for TestNG